### PR TITLE
Fix #46 Support for volumes with 3 parts

### LINKED ISSUE #46: Support for volume options
## Please describe what you would like to see in this project

Due to [this check in argsbuilder](https://github.com/arcalot/arcaflow-engine-deployer-podman/blob/fb81c72a870e2ed5ccb232f7f89fed145793c240/internal/argsbuilder/argsbuilder.go#L22), only volumes passed as `./source:/container-dir` are supported.

## Please describe your use case

Options are required SELinux re-labeling. My resulting volume configuration looks like so: `./source:/container-dir:z`.

Note that several options can be passed for a volume as a [comma separated string](https://docs.podman.io/en/latest/markdown/podman-run.1.html#volume-v-source-volume-host-dir-container-dir-options).

Here is my config.yaml file:
```
deployers:
  image: 
    deployer_name: podman
    deployment:
      imagePullPolicy: Never
      host: 
        Binds:
          - ./builder/go-modules:/root/go/pkg/mod:z
          - ./output:/output:z
          - ../codeql:/beagle-codeql-packs:z
  python:
    deployer_name: python
log:
  level: debug
```

### PR DESCRIPTION
**Pull request by rh-tguittet**
## Changes introduced with this PR

Fix for issue #46, this is needed for selinux enabled distros.

This enables support for 2 and 3 parts volumes:
- 2 parts: `./local:/in-container`
- 3 parts, 3rd part being security options: `./local:/in-container:z`

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by webbnh — APPROVED** [review]
Assuming that the three-token case works like the two-token case, this seems fine.

**Comment by rh-tguittet** [comment]
Bump, would love to be able to run this locally for testing :)

**Comment by webbnh** [comment]
Hi Thibault, I think this PR is waiting for someone to write some tests for it.  I don't think we were going to ask you to do it, but none of us have gotten around to it, yet, either...so, this PR is languishing.  Sorry!

**Comment by rh-tguittet** [comment]
@webbnh I have no issues on testing when adding `:Z` to the volumes list. I cannot test on MacOS (so let me know if it's different).

**Review by webbnh — CHANGES_REQUESTED** [review]
@rh-tguittet, thanks for the update!

However, we should retain the old test (without the `:Z`) and add a _new_ test for that case.

Also, are there other cases we should test (like `:z`, `:ro`, and/or multiple options, like `:z,ro,noexec`)?

I'll take care of these if you want.  (I'm currently doing other work in that file.)

**Comment by webbnh** [comment]
#52 now supersedes this PR -- I've rebased this branch on the end of `main` and piled a bunch of commits on top of it.  🙂

**Pull request closed without merging**
